name: PR

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: pr-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Install docker-compose
        run: |
          cd contract
          yarn install

      - name: Run contract tests
        run: |
          cd contract
          yarn test

      - name: Run lint check
        run: |
          git clone --branch "${{ steps.set-branch.outputs.branch }}" https://github.com/agoric-labs/agoric-to-axelar-local.git

      - name: Install dependencies
        run: |
          cd agoric-to-axelar-local
          npm install

      - name: Build project
        run: |
          cd agoric-to-axelar-local
          npm run build

      - name: Start Chains and set Relayer
        run: |
          cd agoric-to-axelar-local/packages/axelar-local-dev-cosmos
          npm run start

      - name: Prepare Env
        run: ./scripts/prepare-env.mjs

      - name: Register AXL in vbankAssets
        run: ./scripts/deploy-contract.mjs
        env:
          script: /usr/src/agoric-sdk/multichain-testing/src/register-interchain-bank-assets.builder.js
          plan: /usr/src/upgrade-test-scripts/eval-register-interchain-bank-assets-plan.json
          assets: '[{"denom":"ibc/2CC0B1B7A981ACC74854717F221008484603BB8360E81B262411B0D830EDE9B0","issuerName":"AXL","decimalPlaces":6}]'

      - name: Verify AXL registration from vStorage
        run: ./scripts/check-vstorage.mjs
        env:
          vStorageUrl: http://localhost/agoric-lcd/agoric/vstorage/data/published.agoricNames.vbankAsset
          valueToFind: ibc/2CC0B1B7A981ACC74854717F221008484603BB8360E81B262411B0D830EDE9B0
          waitInSeconds: 30

      - name: Deploy Axelar GMP contract
        run: ./scripts/deploy-contract.mjs
        env:
          script: /usr/src/upgrade-test-scripts/contract/proposal/init-axelar-gmp.js
          plan: /usr/src/upgrade-test-scripts/startAxelarGmp-plan.json

      - name: Verify Axelar GMP contract installation from vStorage
        run: ./scripts/check-vstorage.mjs
        env:
          vStorageUrl: http://localhost/agoric-lcd/agoric/vstorage/data/published.agoricNames.instance
          valueToFind: axelarGmp
          waitInSeconds: 30
